# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('hispanic', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('stem', models.BooleanField()),
                ('arts', models.BooleanField()),
                ('community', models.BooleanField()),
            ],
        ),
    ]
