# Generated by Django 2.1 on 2017-11-04 11:20

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('gpa', models.IntegerField(default=0)),
                ('number_of_AP_courses', models.IntegerField(default=0)),
                ('Do_you_consider_yourself_hispanic', models.NullBooleanField()),
                ('athletics', models.BooleanField()),
                ('score', models.IntegerField(default=builtins.sum)),
                ('STEM', models.BooleanField()),
                ('arts', models.BooleanField()),
                ('community_Service', models.BooleanField()),
                ('personal_Statement', models.CharField(max_length=7500)),
                ('Parent_or_Guardian_Name', models.CharField(max_length=50)),
                ('Parent_or_guardian_accept', models.BooleanField()),
            ],
        ),
    ]
