# Generated by Django 2.1 on 2017-11-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='score',
        ),
    ]
