# Generated by Django 2.1 on 2017-11-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='community',
            new_name='Do_you_consider_yourself_hispanic',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='hispanic',
            new_name='Parent_or_guardian_accept',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='stem',
            new_name='STEM',
        ),
        migrations.AddField(
            model_name='nominee',
            name='Parent_or_guardian_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='community_service',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='personal_statement',
            field=models.CharField(default=0, max_length=7500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='student_accept',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
