# Generated by Django 2.1 on 2017-11-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171104_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
