# Generated by Django 2.1 on 2017-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_nominee_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='student_Accept',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
