# Generated by Django 2.1 on 2017-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_nominee_student_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
