# Generated by Django 2.1 on 2017-11-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171104_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
