# Generated by Django 2.1 on 2017-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171104_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='SAT_Scores',
            field=models.IntegerField(default=0),
        ),
    ]
