# Generated by Django 2.1 on 2017-11-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20171104_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='certificates',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
