# Generated by Django 2.1 on 2017-11-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_nominee_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='Do_you_consider_yourself_hispanic',
            field=models.NullBooleanField(),
        ),
    ]
