# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171104_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name=b'Parent_or_guardian_accept',
            new_name='Parent_or_Guardian_Accept',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name=b'Parent_or_guardian_name',
            new_name='Parent_or_Guardian_Name',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name=b'community_service',
            new_name='community_Service',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name=b'personal_statement',
            new_name='personal_Statement',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name=b'certificates',
        ),
        migrations.RemoveField(
            model_name='nominee',
            name=b'student_accept',
        ),
    ]
