# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171104_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='gpa',
            field=models.CharField(default='3', max_length=4),
        ),
        migrations.AddField(
            model_name='nominee',
            name='number_of_AP_courses',
            field=models.IntegerField(default=0),
        ),
    ]
