# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171104_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominee',
            name='gpa',
            field=models.CharField(default=' ', max_length=4),
        ),
    ]
